export default {
  products: [
    {
      _id: "1",
      brand: "Patagonia",
      name: "Capilene Cool Daily Graphic Shirt",
      category: "Shirts",
      image: "/images/product-1.png",
      price: 45.0,
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      brand: "The North Face",
      name: "Thermoball Eco Hoodie",
      category: "Jackets",
      image: "/images/product-2.png",
      price: 176.0,
      rating: 5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      brand: "Ternua",
      name: "Luxon Pant",
      category: "Pants",
      image: "/images/product-3.png",
      price: 150,
      rating: 3.5,
      numReviews: 10,
      countInStock: 0,
    },
    {
      _id: "4",
      brand: "The North Face",
      name: "Reaxion Easy Tee",
      category: "Shirts",
      image: "/images/product-4.png",
      price: 21.0,
      rating: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      brand: "Trangoworld",
      name: "Prote FI",
      category: "Pants",
      image: "/images/product-5.png",
      price: 106.0,
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      brand: "Haglöfs",
      name: "L.I.M Comp Jacket",
      category: "Jackets",
      image: "/images/product-6.png",
      price: 186.45,
      rating: 1.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
